### PR TITLE
Fix logic bug

### PR DESCRIPTION
**Pull request by Emerentius**
When looking for optimisations I found a bug in the solver. It occasionally overrides entries when it finds hidden singles for different rows/columns/fields that overlap a certain cell. That invalidated the `cover.possibilities_count` and `cover.covered` caches and caused it to sometimes find invalid solutions.

This pull request fixes that error and adds tests for the correct solutions of the medium and hard sudokus (1st commit) and optimises a bit (2nd, 3rd commit) to recover some of the performance.

Still, there's a large pessimisation in the case of finding a solution to hard sudokus.
There's a chance that the change in commit 3 is only beneficial for this set of sudokus. Could use more test sudokus.

```
 name                      before.txt ns/iter  after.txt ns/iter  diff ns/iter   diff %
 easy_solve                8,490,519           6,648,986            -1,841,533  -21.69%
 easy_solve_at_most_100    8,717,252           6,788,232            -1,929,020  -22.13%
 easy_solve_one            8,479,069           6,639,941            -1,839,128  -21.69%
 easy_solve_unique         8,712,039           6,779,761            -1,932,278  -22.18%
 hard_solve                114,114,022         182,841,875          68,727,853   60.23%
 hard_solve_at_most_100    584,671,848         356,266,530        -228,405,318  -39.07%
 hard_solve_one            114,135,495         183,379,712          69,244,217   60.67%
 hard_solve_unique         204,152,729         356,325,735         152,173,006   74.54%
 medium_solve              12,130,669          8,721,224            -3,409,445  -28.11%
 medium_solve_at_most_100  21,229,183          9,384,948           -11,844,235  -55.79%
 medium_solve_one          12,121,422          8,716,104            -3,405,318  -28.09%
 medium_solve_unique       12,430,353          9,376,291            -3,054,062  -24.57%
```

### CODE REVIEW

**Comment by aochagavia** [comment]
Great! Thanks for the fix!

**Comment by aochagavia** [comment]
By the way, would you mind if I made you collaborator of this repository? After all, you have contributed almost all the code.

**Comment by Emerentius** [comment]
Would that also include crates.io push rights?
Either way, I'm fine with it. There's still a lot I'd like to improve if I can free the time and not just in the speed department.

I'd also propose pushing the new version as 0.2.1 and yank 0.2 as its known bad.

**Comment by aochagavia** [comment]
Great. I just pushed 0.2.1, yanked 0.2.0, added you as a collaborator of this repository and as owner of the crate on crates.io 😄

**Pull request merged**
